name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        if: always()
        run: |
          npm install
          npm install -g allure-commandline --save-dev
     
      - name: Run Test
        if: always()
        run: npm test
        continue-on-error: true
        env:
          CI: true
